site_name: tools
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.code.select

# plugins:
  # - mkdocs-jupyter
  # - plotly


markdown_extensions:
  markdown.extensions.attr_list:
  markdown.extensions.tables:
  markdown.extensions.md_in_html:
  toc:
    permalink: true
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
  pymdownx.betterem:
  pymdownx.blocks.details:
  pymdownx.blocks.admonition:
    types:
    - note
    - info
    - tip
    - warning
    - danger
  pymdownx.blocks.tab:
    alternate_style: True
  mdx_include:
  pymdownx.highlight:
    anchor_linenums: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - Section:
    - Page 1: section/1.md
    - Page n: section/2.md
  - Misc:
    - locust: misc/locust.md
    - docker: misc/docker.md
    - clis: misc/clis.md
    - rust: misc/rust.md
    - nvidia: misc/nvidia.md
    - vscode: misc/vscode.md
    - gcc/g++: misc/gcc_g++.md
    - wsl: misc/wsl.md
    - software: misc/software.md
    # - Page n: misc/2.md

  # - Notebook: 
  #   - Page 1: code/notebook.ipynb